version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # Jaeger thrift compact
      - "6832:6832/udp" # Jaeger thrift binary
      - "14250:14250" # Model/collector gRPC
      - "16686:16686" # Web UI
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    networks:
      - monitoring-net
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    # command: -config.file=/etc/loki/local-config.yml
    networks:
      - monitoring-net

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./logs:/var/log/app # Mount your local logs directory
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3030:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - monitoring-net
    depends_on:
      - loki

networks:
  monitoring-net:
    driver: bridge
