version: "3"

services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    # command: -config.file=/etc/loki/local-config.yml
    networks:
      - loki-net

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./logs:/var/log/app # Mount your local logs directory
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-net

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3030:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - loki-net
    depends_on:
      - loki

networks:
  loki-net:
    driver: bridge
