server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: hono-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: hono
          environment: development
          __path__: /var/log/app/*.log # This matches the mounted volume path

    pipeline_stages:
      - json: # Parse JSON logs from Pino
          expressions:
            timestamp: time
            level: level
            method: method
            path: path
            status: status
            duration: duration
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          method:
          status:
